# Basic Site Settings
locale            : "en-US"
site_theme        : "default"
title             : "Dr. Oussama Hadoune | Electronics Researcher"
title_separator   : "-"
name              : &name "Oussama Hadoune"
description       : &description "Post-doctoral Researcher in Electronic Systems and Energy Harvesting at École des Mines de Saint-Étienne."
url               : "https://hadouneoussama.github.io" 
baseurl           : "" 
repository        : "HadouneOussama/HadouneOussama.github.io"

# Site Author
author:
  avatar           : "bio-photo.jpg" # Make sure to upload your photo to /images/ and name it this
  name             : "Oussama Hadoune"
  pronouns         : "He/Him"
  bio              : "PhD in Embedded Electronics."
  location         : "Gardanne, France"
  employer         : "École des Mines de Saint-Étienne"
  email            : "Hadouneoussama@gmail.com" 

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=FVBkGoMAAAAJ&hl=fr " # Add your link here if you have one
  orcid            : "https://orcid.org/0000-0003-0843-2767" # Add your ORCID link here
  linkedin         : "https://www.linkedin.com/in/oussama-hadoune-8a4232155/"
  researchgate     : "https://www.researchgate.net/profile/Oussama-Hadoune?ev=hdr_xprf" 

  # Repositories and software development
  github           : "HadouneOussama"
  stackoverflow    : "" 

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Analytics
analytics:
  provider         : "false"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - Gemfile
  - node_modules
  - package.json
  - README
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

# Collections Settings (DO NOT REMOVE)
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults for Layouts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
